In [3]:
import spacy
!python -m spacy download en_core_web_md
nlp=spacy.load('en_core_web_md')

     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
     --- ------------------------------------ 2.9/33.5 MB 20.6 MB/s eta 0:00:02
     -------- ------------------------------- 7.1/33.5 MB 21.3 MB/s eta 0:00:02
     ---------- ----------------------------- 8.9/33.5 MB 16.9 MB/s eta 0:00:02
     ----------- --------------------------- 10.2/33.5 MB 13.3 MB/s eta 0:00:02
     ----------------- --------------------- 14.9/33.5 MB 15.4 MB/s eta 0:00:02
     ------------------------- ------------- 22.3/33.5 MB 18.8 MB/s eta 0:00:01
     ------------------------------------ -- 31.5/33.5 MB 22.6 MB/s eta 0:00:01
     ---------------------------------------- 33.5/33.5 MB 22.1 MB/s  0:00:01
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_md')


In [4]:
nlp(u'lion').vector

array([-0.76275  , -0.2074   ,  0.32124  , -0.45817  , -0.36041  ,
        0.60152  ,  0.74492  ,  0.079701 , -0.23428  ,  0.31224  ,
       -0.43189  ,  0.20746  , -0.40774  , -0.2538   , -0.12308  ,
       -0.39652  ,  0.2361   ,  0.20473  ,  0.49645  ,  0.26983  ,
       -0.45623  ,  0.20879  , -0.0027486,  0.050435 , -0.003348 ,
       -0.088146 , -0.53855  ,  0.42507  , -0.70535  , -0.31984  ,
       -0.56023  , -0.042877 ,  0.31083  , -0.23038  ,  0.43657  ,
        0.18436  ,  0.52997  , -0.1038   ,  0.010579 ,  0.5373   ,
       -0.64911  ,  0.15171  , -0.13305  , -0.17798  ,  0.083277 ,
       -0.15615  , -0.1446   , -0.27032  ,  0.19693  ,  0.22867  ,
       -0.5745   ,  0.16468  ,  0.029028 ,  0.66735  , -0.13859  ,
        0.51194  , -0.029928 ,  0.11792  , -0.15589  ,  0.69151  ,
        0.19838  ,  0.032428 ,  0.37526  ,  0.099998 , -0.48631  ,
       -0.13605  ,  0.5295   , -0.089214 ,  0.34458  ,  0.19393  ,
        0.012607 , -0.1999   , -0.38105  , -0.05991  , -0.8103

In [5]:
doc=nlp(u"the quick brown fox jumped over the lazy dogs.")
doc.vector

array([-6.97969019e-01,  5.56670018e-02, -1.62355408e-01,  2.68360879e-02,
       -9.58139636e-03, -2.15498973e-02, -2.48151012e-02, -1.04111791e-01,
        1.09173097e-01,  1.64876401e+00, -8.64830017e-02, -9.60250050e-02,
       -6.10291585e-02, -1.34389028e-02, -1.50561988e-01,  9.28654969e-02,
       -1.34864897e-01,  8.72585893e-01, -1.22531809e-01, -1.88338920e-01,
       -6.95055947e-02,  6.75773025e-02,  7.23951012e-02, -2.42390200e-01,
       -3.19726020e-02, -1.53924689e-01, -1.00833908e-01, -3.65620442e-02,
       -9.96995121e-02, -2.87402004e-01, -2.31279328e-01,  1.94752514e-01,
        1.13083087e-01, -8.84450302e-02,  1.84483200e-01,  1.19909093e-01,
       -1.52591199e-01,  1.30020012e-03, -2.64751583e-01,  3.17928940e-02,
        1.35594696e-01,  2.74599949e-03, -8.38430375e-02,  2.13983003e-02,
        1.69815883e-01, -3.98678072e-02, -9.36224982e-02, -1.14555992e-01,
        5.26507981e-02, -6.80560023e-02, -2.47021005e-01,  1.88996404e-01,
       -1.35233002e-02, -

In [6]:
tokens=nlp(u'lion cat pet')
tokens

lion cat pet

In [7]:
for token1 in tokens:
    for token2 in tokens:
        print(token1.text,token2.text,token1.similarity(token2))

lion lion 1.0
lion cat 0.31077107787132263
lion pet 0.31077107787132263
cat lion 0.31077107787132263
cat cat 1.0
cat pet 1.0
pet lion 0.31077107787132263
pet cat 1.0
pet pet 1.0


In [8]:
nlp(u'lion').similarity(nlp(u'dandelion'))

0.344340443611145

In [9]:
tokens=nlp(u'like love hate')
tokens

like love hate

In [10]:
for token1 in tokens:
    for token2 in tokens:
        print(token1.text,token2.text,token1.similarity(token2))

like like 1.0
like love 1.0
like hate 1.0
love like 1.0
love love 1.0
love hate 1.0
hate like 1.0
hate love 1.0
hate hate 1.0


In [11]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...


True

In [12]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid=SentimentIntensityAnalyzer()

In [13]:
a='This is a good movie'
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.508, 'pos': 0.492, 'compound': 0.4404}

In [15]:
a='This was the best, most awesome movie ever made!!!'
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.425, 'pos': 0.575, 'compound': 0.8877}

In [16]:
a='This was the worst film to ever disgrace the screen'
sid.polarity_scores(a)

{'neg': 0.477, 'neu': 0.523, 'pos': 0.0, 'compound': -0.8074}

In [18]:
import numpy as np
import pandas as pd
df=pd.read_csv(r"C:\Users\Administrator\Advanced AI\amazonreviews.tsv",sep='\t')
df.head()

label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [19]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [20]:
df.dropna(inplace=True)

In [21]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [23]:
blanks=[]
for i,lb,rv in df.itertuples():
    if type(rv)==str:
        if rv.isspace():
            blanks.append(i)
df.drop(blanks,inplace=True)
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [24]:
sid.polarity_scores(df.loc[0]['review'])
df.loc[0]['label']

'pos'

In [26]:
df['scores']=df['review'].apply(lambda review:sid.polarity_scores(review))
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...

In [27]:
df['component']=df['scores'].apply(lambda score_dict:score_dict['compound'])
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  component  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...     0.9454  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...     0.8957  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...     0.9858  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...     0.9814  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...     0.9781

In [28]:
sid.polarity_scores(df.loc[0]['review'])
df.loc[0]['scores']

{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'compound': 0.9454}

In [32]:
df['comp_score']=df['component'].apply(lambda c:'pos'if c>=0 else 'neg')
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  component comp_score  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...     0.9454        pos  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...     0.8957        pos  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...     0.9858        pos  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...     0.9814        pos  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...     0.9781        pos

In [35]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix 
accuracy_score(df['label'],df['comp_score'])

0.7098

In [36]:
print(confusion_matrix(df['label'],df['comp_score']))

[[2630 2467]
 [ 435 4468]]


In [37]:
print(classification_report(df['label'],df['comp_score']))

              precision    recall  f1-score   support

         neg       0.86      0.52      0.64      5097
         pos       0.64      0.91      0.75      4903

    accuracy                           0.71     10000
   macro avg       0.75      0.71      0.70     10000
weighted avg       0.75      0.71      0.70     10000

